### ISSUE TITLE
吾爱破解签到失效补充

### ISSUE THREAD

**Issue by 961739124** [HeiDaotu/WFRobertQL#6]
cookie 变为 home.php。
![屏幕截图 2023-10-07 234150](https://github.com/HeiDaotu/WFRobertQL/assets/100020034/749313df-b832-4154-9eab-1c52e1bd6962)

**Comment by WhiteCjy** [comment]
这个也失效了

**Comment by HeiDaotu** [comment]
签到算法更换，暂未处理 #5
