### ISSUE TITLE
会支持哔哩哔哩签到吗？

### ISSUE THREAD

**Issue by Hello-XPH** [HeiDaotu/WFRobertQL#8]

**Comment by HeiDaotu** [comment]
暂未开发，可以尝试使用[BiliOutils](https://bo.js.cool/)
项目地址：[catlair/BiliOutils](https://github.com/catlair/BiliOutils)
项目文档：[BiliOutils](https://bo.js.cool/)

**Comment by Hello-XPH** [comment]
好的谢谢
